---
- hosts: all
  remote_user: juan
#  become: true

  tasks:
    - name: update and upgrade
      become: true
      apt:
        upgrade: yes
        update_cache: yes
#        cache_valid_time: 86400
